import type { DetailPageData } from "./service-pages";
import image1 from "../../public/video/common/img1.jpg";
import image2 from "../../public/video/common/img2.jpg";
import image3 from "../../public/video/common/img3.jpg";
import image4 from "../../public/video/common/img4.jpg";
import image5 from "../../public/video/common/img5.jpg";
import image6 from "../../public/video/common/img6.jpg";
import image7 from "../../public/video/common/img7.jpg";

const images = [image1, image2, image3, image4, image5, image6, image7];
const imageAlts = [
  "A broad landscape representing connected public and business services",
  "People using a modern digital service",
  "A connected workspace supporting essential operations",
  "Urban infrastructure and transport links",
  "A customer-facing retail environment",
  "Travel and hospitality in a changing landscape",
  "A bright community and learning environment",
];

const entries = [
  { slug: "healthcare", title: "Healthcare", description: "Connect care teams, improve patient access and make clinical workflows easier to navigate with secure, accessible digital services.", focus: "patient access, care coordination and clinical workflows", audience: "healthcare providers and organisations supporting care delivery", offerings: ["Patient and service portals", "Care pathway coordination", "Clinical workflow tools", "Health system integration", "Accessible digital experiences", "Data security and governance"] },
  { slug: "fintech", title: "FinTech", description: "Build trusted financial products that make onboarding, payments and account management clearer for customers and simpler to operate.", focus: "digital financial products and trusted transactions", audience: "fintech businesses and financial product teams", offerings: ["Digital account experiences", "Payments and transaction flows", "Customer onboarding", "Financial data integration", "Fraud and risk workflows", "Security and regulatory controls"] },
  { slug: "real-estate", title: "Real Estate", description: "Bring property information, customer journeys and asset operations together through digital platforms designed for buyers, tenants and teams.", focus: "property services, customer journeys and asset operations", audience: "property managers, developers and real estate businesses", offerings: ["Property search and discovery", "Buyer and tenant portals", "Asset and facilities workflows", "Property data integration", "Digital transaction services", "Portfolio reporting"] },
  { slug: "iot", title: "IoT", description: "Connect connected devices with operational systems to help teams monitor assets, understand activity and respond with better information.", focus: "connected assets and operational information", audience: "organisations managing devices, equipment and distributed operations", offerings: ["Device and gateway integration", "Telemetry and event processing", "Asset monitoring dashboards", "IoT cloud architecture", "Device identity and security", "Alerts and operational workflows"] },
  { slug: "edtech", title: "EdTech", description: "Create accessible learning and administration platforms that help learners, educators and institutions stay connected.", focus: "accessible learning and education administration", audience: "education providers and learning technology teams", offerings: ["Learning management experiences", "Learner and educator portals", "Course and content workflows", "Student system integration", "Accessibility and inclusion", "Learning insight and reporting"] },
  { slug: "utility", title: "Utility", description: "Improve essential customer and operational services with reliable platforms for service requests, asset information and field teams.", focus: "essential services, customer operations and field work", audience: "utility providers and infrastructure operators", offerings: ["Customer self-service", "Service and outage communications", "Field operations tools", "Asset and network data", "Billing and account integrations", "Operational monitoring"] },
  { slug: "retail-ecommerce", title: "Retail & E-commerce", description: "Connect product discovery, purchasing and fulfilment across channels to make shopping more useful for customers and manageable for teams.", focus: "connected shopping, commerce and fulfilment journeys", audience: "retailers and brands growing digital commerce", offerings: ["Digital commerce storefronts", "Product catalogue and search", "Checkout and payment flows", "Order and fulfilment integration", "Customer loyalty experiences", "Commerce analytics"] },
  { slug: "logistics-supply-chain", title: "Logistics & Supply Chain", description: "Bring planning, tracking and delivery information together so teams can respond faster and provide customers with clearer updates.", focus: "planning, visibility and supply chain coordination", audience: "logistics providers, distributors and supply chain teams", offerings: ["Shipment visibility platforms", "Fleet and route workflows", "Warehouse system integration", "Inventory and order data", "Customer tracking experiences", "Operational analytics"] },
  { slug: "manufacturing", title: "Manufacturing", description: "Connect production systems and operational data to give teams a clearer view of performance, quality and the work ahead.", focus: "production visibility and connected operations", audience: "manufacturers modernising plant and business systems", offerings: ["Production workflow applications", "Equipment and IoT integration", "Quality and traceability tools", "ERP and shop-floor connectivity", "Operational dashboards", "Predictive maintenance foundations"] },
  { slug: "travel-hospitality", title: "Travel & Hospitality", description: "Make planning, booking and service journeys easier for guests while helping teams coordinate the operations behind each experience.", focus: "guest journeys, booking and service operations", audience: "travel operators, hotels and hospitality brands", offerings: ["Search and booking experiences", "Guest and traveller applications", "Reservation system integration", "Personalised service workflows", "Loyalty and communication tools", "Demand and operations insight"] },
  { slug: "media-entertainment", title: "Media & Entertainment", description: "Help audiences find and enjoy content while connecting publishing, rights and distribution workflows for media teams.", focus: "content discovery, publishing and audience engagement", audience: "media organisations, publishers and entertainment platforms", offerings: ["Content platforms and publishing", "Audience and subscription journeys", "Media asset management", "Rights and distribution workflows", "Streaming service integrations", "Engagement analytics"] },
  { slug: "automotive", title: "Automotive", description: "Modernise customer and operational experiences across vehicle sales, ownership, connected services and mobility operations.", focus: "vehicle ownership, customer service and connected mobility", audience: "automotive brands, suppliers and mobility providers", offerings: ["Vehicle discovery and retail", "Owner and service portals", "Connected vehicle integrations", "Dealer and aftersales workflows", "Fleet and mobility platforms", "Operational data services"] },
  { slug: "energy-renewables", title: "Energy & Renewables", description: "Support a changing energy landscape with connected customer services, asset insight and digital tools for distributed operations.", focus: "energy assets, customer services and renewable operations", audience: "energy providers and renewable infrastructure teams", offerings: ["Energy customer platforms", "Renewable asset monitoring", "Smart meter data services", "Field and maintenance workflows", "Grid and partner integration", "Performance and sustainability reporting"] },
  { slug: "government-public-sector", title: "Government & Public Sector", description: "Make public services easier to access and operate with secure digital journeys designed around residents, service teams and policy needs.", focus: "accessible public services and secure case workflows", audience: "government departments, councils and public service teams", offerings: ["Resident and citizen services", "Case and application workflows", "Public service accessibility", "Legacy platform integration", "Secure data exchange", "Service performance insight"] },
  { slug: "financial-services", title: "Financial Services", description: "Improve banking, insurance and financial operations with secure digital experiences that make important customer tasks easier to complete.", focus: "trusted customer journeys and financial operations", audience: "banks, insurers and established financial organisations", offerings: ["Online account services", "Customer onboarding and identity", "Claims and service workflows", "Core system integration", "Financial data and reporting", "Security and compliance support"] },
  { slug: "retail-commerce", title: "Retail & Commerce", description: "Join in-store and digital operations to give customers a consistent experience and teams a better view of products, orders and service.", focus: "omnichannel customer and retail operations", audience: "retailers improving the connection between stores and digital channels", offerings: ["Omnichannel customer journeys", "Store operations applications", "Product and inventory integration", "Order management", "Customer service tools", "Retail performance insight"] },
];

export const industryPages: DetailPageData[] = entries.map((item, index) => ({
  ...item,
  eyebrow: "Industry expertise",
  headline: "Technology for",
  highlight: `${item.title}.`,
  image: images[index % images.length],
  imageAlt: imageAlts[index % imageAlts.length],
}));
