import type { DetailPageData } from "./service-pages";
import image1 from "../../public/video/common/img1.jpg";
import image2 from "../../public/video/common/img2.jpg";
import image3 from "../../public/video/common/img3.jpg";
import image4 from "../../public/video/common/img4.jpg";
import image5 from "../../public/video/common/img5.jpg";
import image6 from "../../public/video/common/img6.jpg";
import image7 from "../../public/video/common/img7.jpg";

const images = [image1, image2, image3, image4, image5, image6, image7];
const imageAlts = [
  "A landscape representing connected data platforms",
  "A modern team environment for application development",
  "A digital workspace for software engineering",
  "Connected infrastructure and cloud technology",
  "A digital commerce environment",
  "A traveller using mobile technology",
  "A collaborative technology workspace",
];

const entries = [
  { slug: "angular", title: "Angular", description: "Develop structured web applications with reusable components, clear boundaries and maintainable patterns for larger products.", focus: "structured TypeScript web applications", audience: "teams building long-lived business and customer portals", offerings: ["Application architecture", "Reusable component development", "Forms and workflow interfaces", "API and identity integration", "Performance optimisation", "Automated quality checks"] },
  { slug: "react-js", title: "React.js", description: "Build interactive interfaces from reusable components, with a front-end architecture matched to your product and team.", focus: "component-based web interfaces", audience: "product teams creating interactive digital experiences", offerings: ["React application foundations", "Reusable interface components", "State and data-flow design", "API integration", "Accessibility and performance", "Component and end-to-end testing"] },
  { slug: "vue-js", title: "Vue.js", description: "Create adaptable web experiences with a progressive framework that can support a focused feature or a complete product interface.", focus: "progressive web application interfaces", audience: "teams adopting Vue for new products or existing platforms", offerings: ["Vue application architecture", "Composition API development", "Reusable component systems", "Routing and state management", "API and service integration", "Testing and performance improvement"] },
  { slug: "next-js", title: "Next.js", description: "Deliver full-stack React experiences with server rendering, routing and performance choices suited to your product and content needs.", focus: "full-stack React applications and websites", audience: "organisations building fast, discoverable digital products", offerings: ["Next.js application architecture", "Server and client rendering", "Routing and content delivery", "API and data integration", "Search and performance foundations", "Deployment and monitoring"] },
  { slug: "typescript", title: "TypeScript", description: "Improve confidence in JavaScript projects with clearer contracts, safer refactoring and shared types across application boundaries.", focus: "safer and more maintainable JavaScript codebases", audience: "engineering teams growing front-end or server-side applications", offerings: ["TypeScript adoption planning", "Typed application architecture", "API contract modelling", "Legacy JavaScript migration", "Shared type libraries", "Build and test integration"] },
  { slug: "java", title: "Java", description: "Build and evolve robust software services with Java, using clear architecture and proven engineering practices for business-critical work.", focus: "reliable JVM applications and services", audience: "organisations running enterprise software and integrations", offerings: ["Java application development", "Service and API architecture", "Enterprise integration", "Modernisation and migration", "Automated testing", "Production support and optimisation"] },
  { slug: "node-js", title: "Node.js", description: "Develop efficient server-side applications and APIs using JavaScript or TypeScript across product and integration workloads.", focus: "event-driven application and API services", audience: "product teams building scalable web back ends", offerings: ["Node.js service architecture", "REST and event APIs", "Identity and access integration", "Data and third-party connections", "Automated testing", "Performance and runtime monitoring"] },
  { slug: "python", title: "Python", description: "Use Python to build application services, automate operational work and connect data capabilities to products and teams.", focus: "application, automation and data services", audience: "organisations building data-rich products and workflows", offerings: ["Python application development", "Service and API implementation", "Workflow automation", "Data processing pipelines", "Testing and security practices", "Deployment and ongoing support"] },
  { slug: "scala", title: "Scala", description: "Develop typed services and data-intensive applications with Scala, combining expressive code with JVM interoperability.", focus: "typed JVM services and data processing", audience: "teams managing complex distributed or data-heavy systems", offerings: ["Scala service development", "Functional application design", "Data processing solutions", "JVM platform integration", "Testing and reliability", "Legacy Scala modernisation"] },
  { slug: "dotnet", title: ".NET", description: "Build and modernise cross-platform applications and services with .NET, integrated with the Microsoft ecosystem where it fits.", focus: "cross-platform Microsoft application services", audience: "organisations extending or modernising .NET systems", offerings: [".NET application development", "ASP.NET Core services", "Microsoft platform integration", "Cloud-native migration", "Automated testing", "Runtime and cost optimisation"] },
  { slug: "php-laravel", title: "PHP / Laravel", description: "Create maintainable web platforms and APIs with PHP and Laravel, from new products to carefully evolved applications.", focus: "web platforms and services built with PHP", audience: "businesses developing or modernising PHP applications", offerings: ["Laravel application architecture", "Web product development", "REST API implementation", "CMS and commerce integration", "Security and test automation", "PHP upgrades and maintenance"] },
  { slug: "go", title: "Go (Golang)", description: "Build efficient services and developer tools with Go, using simple deployment and concurrency where they benefit your systems.", focus: "efficient cloud and platform services", audience: "engineering teams building APIs and distributed services", offerings: ["Go service architecture", "Concurrent API development", "Cloud-native workloads", "Platform and tooling development", "Performance and reliability testing", "Deployment automation"] },
  { slug: "flutter", title: "Flutter", description: "Create consistent cross-platform mobile applications from a shared codebase, with native integrations where the product requires them.", focus: "cross-platform mobile experiences", audience: "organisations building mobile products for iOS and Android", offerings: ["Flutter product foundations", "Shared mobile interface development", "Native device integration", "Mobile API connectivity", "Platform-specific testing", "App store release support"] },
  { slug: "kotlin", title: "Kotlin", description: "Develop modern Android applications and backend services with Kotlin, using language features to keep code expressive and maintainable.", focus: "native Android applications and Kotlin services", audience: "teams building Android-first digital products", offerings: ["Android application architecture", "Native interface development", "Kotlin service development", "Device and platform integration", "Quality and performance testing", "Play Store release support"] },
  { slug: "swift-ios", title: "Swift (iOS)", description: "Build native Apple applications with Swift, designed around iOS conventions, device capabilities and the needs of your users.", focus: "native iOS and Apple platform experiences", audience: "organisations creating high-quality iPhone and iPad applications", offerings: ["iOS application architecture", "Swift interface development", "Apple platform integrations", "Secure data and API access", "Device and accessibility testing", "App Store release support"] },
  { slug: "react-native", title: "React Native", description: "Deliver mobile apps for iOS and Android with React Native, sharing product logic while retaining access to native capabilities.", focus: "shared-code mobile applications", audience: "product teams supporting iOS and Android experiences", offerings: ["React Native app foundations", "Shared mobile interface development", "Native module integration", "Mobile API and identity", "Device and release testing", "Application store delivery"] },
  { slug: "django", title: "Django", description: "Build secure Python web applications with Django, using its conventions to deliver useful products and admin workflows efficiently.", focus: "secure Python web applications", audience: "teams creating data-backed websites and internal tools", offerings: ["Django application architecture", "Model and data design", "Admin and workflow development", "Authentication and permissions", "API and service integration", "Testing and deployment"] },
  { slug: "spring-boot", title: "Spring Boot", description: "Develop production-ready Java services with Spring Boot, shaped around your integration, transaction and operational requirements.", focus: "production-ready Java services", audience: "organisations developing enterprise APIs and distributed applications", offerings: ["Spring Boot service design", "REST and event-driven APIs", "Data and transaction handling", "Identity and enterprise integration", "Observability and testing", "Deployment and service improvement"] },
  { slug: "mysql-mongodb", title: "MySQL / MongoDB", description: "Select, design and operate relational or document databases around the data structures, consistency and access patterns your product needs.", focus: "reliable relational and document data stores", audience: "teams designing or improving application data platforms", offerings: ["Database needs assessment", "Schema and document modelling", "MySQL implementation", "MongoDB implementation", "Migration and performance tuning", "Backup, access and monitoring"] },
  { slug: "devops-ci-cd", title: "DevOps & CI/CD", description: "Connect engineering and operations through automated builds, repeatable environments and release practices that make delivery more dependable.", focus: "automating software delivery and operations", audience: "teams improving release confidence and engineering flow", offerings: ["Delivery pipeline assessment", "Build and test automation", "Infrastructure as code", "Release and deployment workflows", "Monitoring and incident readiness", "Developer experience improvement"] },
  { slug: "ai-data", title: "AI & Data", description: "Connect data platforms, analytics and practical AI capabilities to help teams make informed decisions and improve business workflows.", focus: "turning governed data into useful intelligence", audience: "organisations exploring AI and modern data platforms", offerings: ["AI use-case discovery", "Data platform architecture", "Data quality and governance", "Machine learning integration", "Generative AI applications", "Evaluation and monitoring"] },
  { slug: "cloud-aws", title: "Cloud & AWS", description: "Design and evolve cloud platforms on AWS, with migration, security and operations aligned to your workload and growth plans.", focus: "secure and resilient AWS cloud workloads", audience: "teams adopting AWS or improving existing cloud services", offerings: ["Cloud readiness assessment", "AWS platform foundations", "Workload migration", "Cloud-native engineering", "Security and reliability", "Cost and operations management"] },
  { slug: "software-platforms", title: "Software Platforms", description: "Choose and connect software platforms around your processes, making sure each tool fits the wider architecture and user experience.", focus: "selecting and connecting business software platforms", audience: "organisations reviewing enterprise and digital platforms", offerings: ["Platform selection and fit", "Solution architecture", "Configuration and extension", "Data and API integration", "Adoption and workflow design", "Platform lifecycle planning"] },
];

export const technologyPages: DetailPageData[] = entries.map((item, index) => ({
  ...item,
  eyebrow: "Technology expertise",
  headline: `Build with ${item.title}`,
  highlight: "for what comes next.",
  image: images[index % images.length],
  imageAlt: imageAlts[index % imageAlts.length],
}));
